import { contextBridge, ipcRenderer } from 'electron';
import type { LiveStreamConfig, ProfileConfig, ProjectPayload, RecordingPayload, ScriptPayload, SharePayload } from '@shared/types';

contextBridge.exposeInMainWorld('electronAPI', {
  listScripts: () => ipcRenderer.invoke('scripts:list'),
  saveScript: (payload: ScriptPayload) => ipcRenderer.invoke('scripts:save', payload),
  deleteScript: (id: string) => ipcRenderer.invoke('scripts:delete', id),
  getScript: (id: string) => ipcRenderer.invoke('scripts:get', id),
  listProjects: () => ipcRenderer.invoke('projects:list'),
  saveProject: (payload: ProjectPayload) => ipcRenderer.invoke('projects:save', payload),
  deleteProject: (id: string) => ipcRenderer.invoke('projects:delete', id),
  listProfiles: (projectId?: string) => ipcRenderer.invoke('profiles:list', projectId),
  saveProfile: (payload: ProfileConfig) => ipcRenderer.invoke('profiles:save', payload),
  listRecordings: (projectId?: string) => ipcRenderer.invoke('recordings:list', projectId),
  saveRecording: (payload: RecordingPayload) => ipcRenderer.invoke('recordings:save', payload),
  listSyncQueue: (projectId?: string) => ipcRenderer.invoke('sync:list', projectId),
  markSynced: (id: string) => ipcRenderer.invoke('sync:mark', id),
  processSyncQueue: (projectId?: string) => ipcRenderer.invoke('sync:process', projectId),
  listStreamConfigs: (projectId?: string) => ipcRenderer.invoke('streams:list', projectId),
  saveStreamConfig: (payload: LiveStreamConfig) => ipcRenderer.invoke('streams:save', payload),
  deleteStreamConfig: (id: string) => ipcRenderer.invoke('streams:delete', id),
  startStreaming: (configId: string) => ipcRenderer.invoke('streams:start', configId),
  stopStreaming: (sessionId: string) => ipcRenderer.invoke('streams:stop', sessionId),
  sendToSlack: (payload: SharePayload) => ipcRenderer.invoke('share:slack', payload),
  sendToNotion: (payload: SharePayload) => ipcRenderer.invoke('share:notion', payload),
  sendToTrello: (payload: SharePayload) => ipcRenderer.invoke('share:trello', payload),
  getRemoteInfo: () => ipcRenderer.invoke('remote:info'),
  updateOverlay: (payload: { alwaysOnTop: boolean; opacity: number }) => ipcRenderer.invoke('overlay:update', payload),
  registerShortcuts: (payload: any) => ipcRenderer.invoke('shortcuts:register', payload),
  onShortcutAction: (callback: (action: string) => void) => ipcRenderer.on('shortcut-action', (_event, action) => callback(action)),
  onRemoteAction: (callback: (action: string) => void) => ipcRenderer.on('remote-control-action', (_event, action) => callback(action)),
  saveMediaBuffer: (payload: { data: ArrayBuffer; extension: string; prefix?: string }) => ipcRenderer.invoke('media:save-buffer', payload),
  applyEyeContact: (videoPath: string) => ipcRenderer.invoke('video:apply-eye-contact', videoPath),
  transcribeVideo: (videoPath: string, language: string) => ipcRenderer.invoke('video:transcribe', videoPath, language),
  wordTrim: (payload: any) => ipcRenderer.invoke('video:wordtrim', payload),
  mixVideo: (payload: any) => ipcRenderer.invoke('video:mix', payload),
  exportVertical: (payload: any) => ipcRenderer.invoke('video:export-vertical', payload),
  suggestBroll: (script: string) => ipcRenderer.invoke('broll:suggest', script),
  suggestShorts: (segments: any) => ipcRenderer.invoke('shorts:suggest', segments)
});
